default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] %>  
  password: <%= ENV['DATABASE_PASSWORD'] %>  
  host: <%= ENV['DATABASE_HOST'] %> 

development:
  <<: *default
  database: sneakers_development

test:
  <<: *default
  database: sneakers_test

production:
  <<: *default
  database: sneakers_production
  username: <%= ENV['DATABASE_USERNAME'] %>  
  password: <%= ENV['DATABASE_PASSWORD'] %> 
  host: <%= ENV['DATABASE_HOST'] %> 
